### PR TITLE
updated CLI step to use working directory

### PR DESCRIPTION
**Pull request by mozts2005**
when using the plugin we found that it was not respecting the working directory option.

### CODE REVIEW

**Comment by mozts2005** [comment]
@madhurig do we have an ETA?

**Review by madhurig — APPROVED** [review]
Thanks for the contribution, the changes look good. We also need to update the task version and extension version before we can publish it. We will do that this week.

**Comment by mozts2005** [comment]
thanks for the update.

**Review by lkillgore — APPROVED** [review]
Looks GTM!

**Pull request merged**
